name: Check for DMI5
on:
  merge_group:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-dmi5:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ParadiseSS13/DMI5Checker@v1
        with:
          icons-path: "icons"
