name: "Round ID Linker"
on:
  issues:
    types: [opened]

jobs:
  link_rounds:
    runs-on: ubuntu-20.04
    steps:
      - uses: shiptest-ss13/round_linker@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          link-url: "https://shiptest.net/stats/rounds/"
